[project]
name = 'DecentralizedID'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.DecentralizedID]
path = 'contracts/DecentralizedID.clar'
clarity_version = 3
epoch = 3.1

[contracts.CredentialReputation]
path = 'contracts/CredentialReputation.clar'
clarity_version = 3
epoch = 3.1

[contracts.CredentialTemplate]
path = 'contracts/CredentialTemplate.clar'
clarity_version = 3
epoch = 3.1

[contracts.CredentialRegistry]
path = 'contracts/CredentialRegistry.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
